apiVersion: v2
name: argocd-applications
description: Argo CD Applications for Django CI/CD
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - argocd
  - gitops
  - cicd
maintainers:
  - name: DevOps Engineer
    email: devops@example.com